# Generated by Django 2.2.2 on 2019-06-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_auto_20190622_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='movie_genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, to='films.Genre'),
        ),
    ]
