# Generated by Django 2.2.2 on 2019-06-23 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_auto_20190622_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='director',
            new_name='directors',
        ),
    ]
