# Generated by Django 2.2.2 on 2019-06-23 00:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_auto_20190622_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cover_url',
            field=models.CharField(blank=True, default='Not found', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='plot_outline',
            field=models.TextField(blank=True, default='Not found', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=1.0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveIntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2020)]),
        ),
    ]
