# Generated by Django 2.2.2 on 2019-07-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_auto_20190622_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumbnail_url',
            field=models.CharField(blank=True, default='Notfound', max_length=200, null=True),
        ),
    ]
