# Generated by Django 2.2.2 on 2019-06-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(blank=True, to='films.Actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cover_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(blank=True, to='films.Director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, to='films.Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='plot_outline',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(blank=True),
        ),
    ]
