# Generated by Django 2.2.2 on 2019-06-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_auto_20190622_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='directors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.AddField(
            model_name='actor',
            name='acted_in',
            field=models.ManyToManyField(blank=True, to='films.Movie'),
        ),
        migrations.AddField(
            model_name='director',
            name='directed_in',
            field=models.ManyToManyField(blank=True, to='films.Movie'),
        ),
        migrations.AddField(
            model_name='genre',
            name='movie_genre',
            field=models.ManyToManyField(blank=True, to='films.Movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3),
        ),
    ]
